"""Staff preset definitions P01–P10 (semantic YAML content for L011)."""

from __future__ import annotations

from orng_led.presets.models import EpisodeCard, PresetDocument

STAFF_PRESET_IDS = tuple(f"P{i:02d}" for i in range(1, 11))

STAFF_LABELS: dict[str, str] = {
    "P01": "Дуже плавний",
    "P02": "Атмосферний",
    "P03": "М'яка динаміка",
    "P04": "Помірний",
    "P05": "Універсальний",
    "P06": "Ритмічний",
    "P07": "Активний",
    "P08": "Енергійний",
    "P09": "Жорсткий",
    "P10": "Максимальний",
}


def _ep(
    index: int,
    *,
    groups: list[str],
    palette: str,
    effect: str,
    speed: float,
    intensity: float,
    transition: str = "soft",
) -> EpisodeCard:
    return EpisodeCard(
        id=f"ep{index}",
        duration_s=18.0,
        groups=groups,
        palette=palette,
        effect=effect,
        speed=speed,
        intensity=intensity,
        transition=transition,
    )


def build_staff_preset(preset_id: str) -> PresetDocument:
    """Return a validated 10×18s staff preset with distinct composition."""
    label = STAFF_LABELS[preset_id]
    episodes = _EPISODES[preset_id]
    if len(episodes) != 10:
        raise ValueError(f"{preset_id} must have exactly 10 episodes")
    if any(ep.duration_s != 18.0 for ep in episodes):
        raise ValueError(f"{preset_id} episodes must be 18s each")
    if any(ep.effect == "static" for ep in episodes):
        # Staff looks must evolve inside each episode (canon §6).
        raise ValueError(f"{preset_id} must not use static-only episodes")
    return PresetDocument(
        id=preset_id,
        label=label,
        hardware_tuned=False,
        builtin=True,
        episodes=episodes,
    )


# Distinct recipes: not just speed multipliers — different groups/palettes/effects.
_EPISODES: dict[str, list[EpisodeCard]] = {
    "P01": [
        _ep(
            1,
            groups=["all_rear"],
            palette="warm_orange",
            effect="breathe",
            speed=0.18,
            intensity=0.45,
            transition="fade",
        ),
        _ep(
            2,
            groups=["par"],
            palette="amber",
            effect="pulse",
            speed=0.2,
            intensity=0.42,
            transition="soft",
        ),
        _ep(
            3,
            groups=["bar"],
            palette="warm_orange",
            effect="wave",
            speed=0.22,
            intensity=0.4,
            transition="fade",
        ),
        _ep(
            4,
            groups=["all_rear"],
            palette="white_warm",
            effect="breathe",
            speed=0.16,
            intensity=0.48,
            transition="soft",
        ),
        _ep(
            5,
            groups=["outer"],
            palette="amber",
            effect="pulse",
            speed=0.2,
            intensity=0.44,
            transition="fade",
        ),
        _ep(
            6,
            groups=["par", "beam"],
            palette="warm_orange",
            effect="mirror_sweep",
            speed=0.15,
            intensity=0.4,
            transition="soft",
        ),
        _ep(
            7,
            groups=["inner", "bar"],
            palette="amber",
            effect="wave",
            speed=0.2,
            intensity=0.46,
            transition="fade",
        ),
        _ep(
            8,
            groups=["all_rear"],
            palette="warm_orange",
            effect="breathe",
            speed=0.18,
            intensity=0.5,
            transition="soft",
        ),
        _ep(
            9,
            groups=["left", "right"],
            palette="white_warm",
            effect="pulse",
            speed=0.17,
            intensity=0.43,
            transition="fade",
        ),
        _ep(
            10,
            groups=["all_rear"],
            palette="warm_orange",
            effect="breathe",
            speed=0.18,
            intensity=0.45,
            transition="fade",
        ),
    ],
    "P02": [
        _ep(
            1,
            groups=["all_rear"],
            palette="cool_blue",
            effect="breathe",
            speed=0.22,
            intensity=0.5,
            transition="fade",
        ),
        _ep(
            2,
            groups=["inner", "bar"],
            palette="mint",
            effect="wave",
            speed=0.25,
            intensity=0.48,
            transition="soft",
        ),
        _ep(
            3,
            groups=["par"],
            palette="violet_orange",
            effect="pulse",
            speed=0.2,
            intensity=0.46,
            transition="fade",
        ),
        _ep(
            4,
            groups=["outer", "bar"],
            palette="cool_blue",
            effect="breathe",
            speed=0.24,
            intensity=0.52,
            transition="soft",
        ),
        _ep(
            5,
            groups=["beam"],
            palette="mint",
            effect="mirror_sweep",
            speed=0.18,
            intensity=0.44,
            transition="fade",
        ),
        _ep(
            6,
            groups=["all_rear"],
            palette="violet_orange",
            effect="wave",
            speed=0.26,
            intensity=0.5,
            transition="soft",
        ),
        _ep(
            7,
            groups=["left", "par"],
            palette="cool_blue",
            effect="pulse",
            speed=0.22,
            intensity=0.47,
            transition="fade",
        ),
        _ep(
            8,
            groups=["right", "bar"],
            palette="mint",
            effect="wave",
            speed=0.24,
            intensity=0.49,
            transition="soft",
        ),
        _ep(
            9,
            groups=["all_rear"],
            palette="cool_blue",
            effect="breathe",
            speed=0.2,
            intensity=0.53,
            transition="fade",
        ),
        _ep(
            10,
            groups=["all_rear"],
            palette="cool_blue",
            effect="breathe",
            speed=0.22,
            intensity=0.5,
            transition="fade",
        ),
    ],
    "P03": [
        _ep(
            1,
            groups=["left", "right"],
            palette="warm_orange",
            effect="mirror_sweep",
            speed=0.3,
            intensity=0.55,
            transition="soft",
        ),
        _ep(
            2,
            groups=["bar"],
            palette="amber",
            effect="wave",
            speed=0.32,
            intensity=0.58,
            transition="soft",
        ),
        _ep(
            3,
            groups=["par"],
            palette="violet_orange",
            effect="pulse",
            speed=0.28,
            intensity=0.54,
            transition="fade",
        ),
        _ep(
            4,
            groups=["left", "bar"],
            palette="warm_orange",
            effect="wave",
            speed=0.34,
            intensity=0.56,
            transition="soft",
        ),
        _ep(
            5,
            groups=["right", "bar"],
            palette="amber",
            effect="wave",
            speed=0.34,
            intensity=0.56,
            transition="soft",
        ),
        _ep(
            6,
            groups=["beam"],
            palette="magenta",
            effect="mirror_sweep",
            speed=0.28,
            intensity=0.52,
            transition="fade",
        ),
        _ep(
            7,
            groups=["outer", "par"],
            palette="warm_orange",
            effect="pulse",
            speed=0.3,
            intensity=0.57,
            transition="soft",
        ),
        _ep(
            8,
            groups=["inner", "bar"],
            palette="violet_orange",
            effect="wave",
            speed=0.33,
            intensity=0.55,
            transition="soft",
        ),
        _ep(
            9,
            groups=["all_rear"],
            palette="amber",
            effect="breathe",
            speed=0.28,
            intensity=0.58,
            transition="fade",
        ),
        _ep(
            10,
            groups=["left", "right"],
            palette="warm_orange",
            effect="mirror_sweep",
            speed=0.3,
            intensity=0.55,
            transition="soft",
        ),
    ],
    "P04": [
        _ep(
            1,
            groups=["all_rear"],
            palette="amber",
            effect="pulse",
            speed=0.4,
            intensity=0.62,
            transition="soft",
        ),
        _ep(
            2,
            groups=["par", "bar"],
            palette="warm_orange",
            effect="wave",
            speed=0.42,
            intensity=0.6,
            transition="soft",
        ),
        _ep(
            3,
            groups=["outer"],
            palette="deep_red",
            effect="pulse",
            speed=0.38,
            intensity=0.58,
            transition="fade",
        ),
        _ep(
            4,
            groups=["inner", "bar"],
            palette="amber",
            effect="chase",
            speed=0.4,
            intensity=0.61,
            transition="soft",
        ),
        _ep(
            5,
            groups=["beam"],
            palette="warm_orange",
            effect="mirror_sweep",
            speed=0.35,
            intensity=0.57,
            transition="soft",
        ),
        _ep(
            6,
            groups=["all_rear"],
            palette="white_warm",
            effect="breathe",
            speed=0.36,
            intensity=0.6,
            transition="fade",
        ),
        _ep(
            7,
            groups=["par"],
            palette="amber",
            effect="pulse",
            speed=0.42,
            intensity=0.63,
            transition="soft",
        ),
        _ep(
            8,
            groups=["bar"],
            palette="warm_orange",
            effect="wave",
            speed=0.44,
            intensity=0.62,
            transition="soft",
        ),
        _ep(
            9,
            groups=["left", "right"],
            palette="deep_red",
            effect="pulse",
            speed=0.4,
            intensity=0.59,
            transition="fade",
        ),
        _ep(
            10,
            groups=["all_rear"],
            palette="amber",
            effect="pulse",
            speed=0.4,
            intensity=0.62,
            transition="soft",
        ),
    ],
    "P05": [
        _ep(
            1,
            groups=["all_rear"],
            palette="warm_orange",
            effect="pulse",
            speed=0.45,
            intensity=0.7,
            transition="soft",
        ),
        _ep(
            2,
            groups=["par", "bar"],
            palette="amber",
            effect="wave",
            speed=0.5,
            intensity=0.68,
            transition="soft",
        ),
        _ep(
            3,
            groups=["all_rear"],
            palette="warm_orange",
            effect="breathe",
            speed=0.4,
            intensity=0.72,
            transition="fade",
        ),
        _ep(
            4,
            groups=["outer", "bar"],
            palette="deep_red",
            effect="pulse",
            speed=0.55,
            intensity=0.65,
            transition="soft",
        ),
        _ep(
            5,
            groups=["all_rear"],
            palette="amber",
            effect="chase",
            speed=0.5,
            intensity=0.7,
            transition="soft",
        ),
        _ep(
            6,
            groups=["par", "beam"],
            palette="warm_orange",
            effect="mirror_sweep",
            speed=0.35,
            intensity=0.66,
            transition="fade",
        ),
        _ep(
            7,
            groups=["all_rear"],
            palette="white_warm",
            effect="pulse",
            speed=0.48,
            intensity=0.6,
            transition="soft",
        ),
        _ep(
            8,
            groups=["inner", "bar"],
            palette="violet_orange",
            effect="wave",
            speed=0.52,
            intensity=0.7,
            transition="soft",
        ),
        _ep(
            9,
            groups=["all_rear"],
            palette="amber",
            effect="breathe",
            speed=0.42,
            intensity=0.74,
            transition="fade",
        ),
        _ep(
            10,
            groups=["all_rear"],
            palette="warm_orange",
            effect="pulse",
            speed=0.45,
            intensity=0.7,
            transition="soft",
        ),
    ],
    "P06": [
        _ep(
            1,
            groups=["bar"],
            palette="magenta",
            effect="chase",
            speed=0.55,
            intensity=0.72,
            transition="soft",
        ),
        _ep(
            2,
            groups=["par"],
            palette="warm_orange",
            effect="pulse",
            speed=0.5,
            intensity=0.7,
            transition="soft",
        ),
        _ep(
            3,
            groups=["bar", "outer"],
            palette="amber",
            effect="chase",
            speed=0.58,
            intensity=0.74,
            transition="soft",
        ),
        _ep(
            4,
            groups=["inner", "bar"],
            palette="violet_orange",
            effect="chase",
            speed=0.56,
            intensity=0.7,
            transition="fade",
        ),
        _ep(
            5,
            groups=["all_rear"],
            palette="magenta",
            effect="wave",
            speed=0.52,
            intensity=0.72,
            transition="soft",
        ),
        _ep(
            6,
            groups=["beam"],
            palette="warm_orange",
            effect="mirror_sweep",
            speed=0.45,
            intensity=0.68,
            transition="soft",
        ),
        _ep(
            7,
            groups=["left", "bar"],
            palette="amber",
            effect="chase",
            speed=0.6,
            intensity=0.73,
            transition="soft",
        ),
        _ep(
            8,
            groups=["right", "bar"],
            palette="magenta",
            effect="chase",
            speed=0.6,
            intensity=0.73,
            transition="soft",
        ),
        _ep(
            9,
            groups=["par", "bar"],
            palette="violet_orange",
            effect="pulse",
            speed=0.54,
            intensity=0.71,
            transition="fade",
        ),
        _ep(
            10,
            groups=["bar"],
            palette="magenta",
            effect="chase",
            speed=0.55,
            intensity=0.72,
            transition="soft",
        ),
    ],
    "P07": [
        _ep(
            1,
            groups=["all_rear"],
            palette="deep_red",
            effect="chase",
            speed=0.65,
            intensity=0.78,
            transition="soft",
        ),
        _ep(
            2,
            groups=["outer", "par"],
            palette="amber",
            effect="pulse",
            speed=0.62,
            intensity=0.76,
            transition="soft",
        ),
        _ep(
            3,
            groups=["bar"],
            palette="magenta",
            effect="wave",
            speed=0.68,
            intensity=0.8,
            transition="soft",
        ),
        _ep(
            4,
            groups=["inner", "outer"],
            palette="warm_orange",
            effect="chase",
            speed=0.66,
            intensity=0.77,
            transition="fade",
        ),
        _ep(
            5,
            groups=["beam"],
            palette="deep_red",
            effect="mirror_sweep",
            speed=0.55,
            intensity=0.74,
            transition="soft",
        ),
        _ep(
            6,
            groups=["left", "right"],
            palette="violet_orange",
            effect="pulse",
            speed=0.64,
            intensity=0.79,
            transition="soft",
        ),
        _ep(
            7,
            groups=["bar", "par"],
            palette="amber",
            effect="chase",
            speed=0.7,
            intensity=0.78,
            transition="soft",
        ),
        _ep(
            8,
            groups=["all_rear"],
            palette="magenta",
            effect="wave",
            speed=0.66,
            intensity=0.8,
            transition="fade",
        ),
        _ep(
            9,
            groups=["outer", "beam"],
            palette="deep_red",
            effect="pulse",
            speed=0.63,
            intensity=0.76,
            transition="soft",
        ),
        _ep(
            10,
            groups=["all_rear"],
            palette="deep_red",
            effect="chase",
            speed=0.65,
            intensity=0.78,
            transition="soft",
        ),
    ],
    "P08": [
        _ep(
            1,
            groups=["all_rear"],
            palette="violet_orange",
            effect="chase",
            speed=0.72,
            intensity=0.84,
            transition="soft",
        ),
        _ep(
            2,
            groups=["par"],
            palette="warm_orange",
            effect="pulse",
            speed=0.7,
            intensity=0.82,
            transition="soft",
        ),
        _ep(
            3,
            groups=["bar"],
            palette="magenta",
            effect="chase",
            speed=0.75,
            intensity=0.86,
            transition="soft",
        ),
        _ep(
            4,
            groups=["beam"],
            palette="amber",
            effect="mirror_sweep",
            speed=0.6,
            intensity=0.8,
            transition="fade",
        ),
        _ep(
            5,
            groups=["outer", "inner"],
            palette="deep_red",
            effect="wave",
            speed=0.73,
            intensity=0.85,
            transition="soft",
        ),
        _ep(
            6,
            groups=["left", "bar"],
            palette="violet_orange",
            effect="chase",
            speed=0.74,
            intensity=0.83,
            transition="soft",
        ),
        _ep(
            7,
            groups=["right", "par"],
            palette="magenta",
            effect="pulse",
            speed=0.71,
            intensity=0.84,
            transition="soft",
        ),
        _ep(
            8,
            groups=["all_rear"],
            palette="warm_orange",
            effect="chase",
            speed=0.76,
            intensity=0.86,
            transition="fade",
        ),
        _ep(
            9,
            groups=["bar", "beam"],
            palette="amber",
            effect="wave",
            speed=0.72,
            intensity=0.82,
            transition="soft",
        ),
        _ep(
            10,
            groups=["all_rear"],
            palette="violet_orange",
            effect="chase",
            speed=0.72,
            intensity=0.84,
            transition="soft",
        ),
    ],
    "P09": [
        _ep(
            1,
            groups=["all_rear"],
            palette="deep_red",
            effect="pulse",
            speed=0.7,
            intensity=0.88,
            transition="soft",
        ),
        _ep(
            2,
            groups=["par"],
            palette="white_warm",
            effect="pulse",
            speed=0.68,
            intensity=0.85,
            transition="cut",
        ),
        _ep(
            3,
            groups=["bar"],
            palette="deep_red",
            effect="chase",
            speed=0.72,
            intensity=0.9,
            transition="soft",
        ),
        _ep(
            4,
            groups=["outer"],
            palette="white_warm",
            effect="wave",
            speed=0.65,
            intensity=0.84,
            transition="soft",
        ),
        _ep(
            5,
            groups=["beam"],
            palette="deep_red",
            effect="mirror_sweep",
            speed=0.55,
            intensity=0.82,
            transition="fade",
        ),
        _ep(
            6,
            groups=["all_rear"],
            palette="deep_red",
            effect="pulse",
            speed=0.74,
            intensity=0.9,
            transition="soft",
        ),
        _ep(
            7,
            groups=["inner", "bar"],
            palette="white_warm",
            effect="chase",
            speed=0.7,
            intensity=0.86,
            transition="cut",
        ),
        _ep(
            8,
            groups=["par", "beam"],
            palette="deep_red",
            effect="pulse",
            speed=0.68,
            intensity=0.88,
            transition="soft",
        ),
        _ep(
            9,
            groups=["left", "right"],
            palette="white_warm",
            effect="wave",
            speed=0.66,
            intensity=0.85,
            transition="soft",
        ),
        _ep(
            10,
            groups=["all_rear"],
            palette="deep_red",
            effect="pulse",
            speed=0.7,
            intensity=0.88,
            transition="soft",
        ),
    ],
    "P10": [
        _ep(
            1,
            groups=["all_rear"],
            palette="warm_orange",
            effect="chase",
            speed=0.8,
            intensity=0.95,
            transition="soft",
        ),
        _ep(
            2,
            groups=["par", "bar"],
            palette="deep_red",
            effect="pulse",
            speed=0.78,
            intensity=0.94,
            transition="soft",
        ),
        _ep(
            3,
            groups=["outer", "inner"],
            palette="magenta",
            effect="wave",
            speed=0.82,
            intensity=0.95,
            transition="soft",
        ),
        _ep(
            4,
            groups=["beam"],
            palette="amber",
            effect="mirror_sweep",
            speed=0.7,
            intensity=0.92,
            transition="fade",
        ),
        _ep(
            5,
            groups=["all_rear"],
            palette="white_warm",
            effect="chase",
            speed=0.85,
            intensity=0.95,
            transition="soft",
        ),
        _ep(
            6,
            groups=["bar"],
            palette="violet_orange",
            effect="chase",
            speed=0.84,
            intensity=0.93,
            transition="soft",
        ),
        _ep(
            7,
            groups=["par"],
            palette="deep_red",
            effect="pulse",
            speed=0.8,
            intensity=0.95,
            transition="soft",
        ),
        _ep(
            8,
            groups=["left", "right"],
            palette="warm_orange",
            effect="wave",
            speed=0.82,
            intensity=0.94,
            transition="fade",
        ),
        _ep(
            9,
            groups=["all_rear"],
            palette="magenta",
            effect="chase",
            speed=0.86,
            intensity=0.95,
            transition="soft",
        ),
        _ep(
            10,
            groups=["all_rear"],
            palette="warm_orange",
            effect="chase",
            speed=0.8,
            intensity=0.95,
            transition="soft",
        ),
    ],
}


def all_staff_presets() -> dict[str, PresetDocument]:
    return {preset_id: build_staff_preset(preset_id) for preset_id in STAFF_PRESET_IDS}
